### ISSUE TITLE
6to5 ponyfills

### ISSUE THREAD

**Issue by stoeffel** [fp-js/fj-map#1]
You should add `require('6to5/polyfill');`.
Tests didn't run on my machine, because `Array.from` was not found.

**Comment by hemanth** [comment]
That wuld result in `6to5` being a dep, rather will use `new Array()` :/ btw we must rename `6to5` to `babeljs`

**Comment by stoeffel** [comment]
> That wuld result in 6to5 being a dep

Oh yes right. I think this is pretty annoying. Why isn't this transpiled correctly?

**Comment by hemanth** [comment]
Checkout the [caveats](https://babeljs.io/docs/usage/caveats/).

**Comment by stoeffel** [comment]
I know. Still annoying :smile:

**Comment by hemanth** [comment]
:cactus:
